site_name: Talking Balance
site_description: The Penny Drops
site_author: Theo Holroyd
copyright: © Copyright 2023 Talking Balance
theme:
  name: material
  custom_dir: overrides
  logo: website/logo.png
nav:
 - Home: index.md
 - Getting Started: gettingStarted.md
 - Download: download.md
 - History: history.md
 - Contact Us: contact.md
plugins: []
